spring:
  datasource:
    driverClassName: MongoDB
  data:
    mongodb:
      uri: mongodb://mongodb/incalc
      database: incalc
      host: mongodb
      port: 27017
jwt:
  secret:
    incalcsecretkey